function renderInbox(){const box=$('#signalInbox');box.innerHTML='';$('#emptyInbox').style.display=signals.length?'none':'block';signals.slice().sort((a,b)=>b.weight-a.weight).forEach((s,i)=>{const row=document.createElement('div');row.className='signal-row-item';row.innerHTML=`<div class="signal-name"><strong>${esc(s.label)}</strong><small>${s.role==='core'?'persistent taste':s.role==='current'?'current curiosity':'ignored'}</small></div><div class="signal-evidence">${s.sources.map(x=>esc(x)).join(' + ')}</div><div class="weight-controls"><button data-delta="-1">−</button><div class="weight-meter"><i style="width:${s.weight*10}%"></i></div><button data-delta="1">+</button></div><select class="role-select"><option value="core" ${s.role==='core'?'selected':''}>CORE</option><option value="current" ${s.role==='current'?'selected':''}>CURRENT</option><option value="muted" ${s.role==='muted'?'selected':''}>MUTED</option></select><button class="remove-signal">×</button>`;row.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>{s.weight=Math.max(1,Math.min(10,s.weight+Number(b.dataset.delta)));save();renderAll()});row.querySelector('select').onchange=e=>{s.role=e.target.value;save();renderAll()};row.querySelector('.remove-signal').onclick=()=>{signals=signals.filter(x=>x!==s);save();renderAll()};box.appendChild(row)})}
function renderSummary(){const top=topClusters();if(!top.length){$('#modelName').textContent='Unbuilt taste';$('#modelSummary').textContent='We need a few signals before the graph can distinguish your core taste from a passing curiosity.';$('#clusterBars').innerHTML='';return}const words=top.slice(0,3).map(x=>title(x[0]));$('#modelName').textContent=words.length>1?`${words[0]} × ${words[1]}`:words[0];$('#modelSummary').textContent=`Built from ${signals.filter(s=>s.role!=='muted').length} active signals. Core taste is weighted more heavily than temporary curiosity.`;const max=top[0][1]||1;$('#clusterBars').innerHTML=top.map(([n,v])=>`<div class="cluster-bar"><div><span>${esc(n)}</span><span>${Math.round(v/max*100)}</span></div><i><span style="width:${Math.round(v/max*100)}%"></span></i></div>`).join('')}
function renderFilters(){const el=$('#categoryFilters');el.innerHTML='';Object.entries(CATEGORIES).forEach(([k,[label]])=>{const b=document.createElement('button');b.textContent=label;b.className=activeTypes.has(k)?'active':'';b.onclick=()=>{activeTypes.has(k)?activeTypes.delete(k):activeTypes.add(k);renderGraph()};el.appendChild(b)})}
function graphData(){const all=classified().filter(e=>activeTypes.has(e.type));if(!signals.length)return{nodes:[],links:[]};let picked;if(mode==='whitespace'){const ghosts=all.filter(e=>e.state==='ghost').slice(0,18);const anchors=all.filter(e=>e.state==='known').slice(0,5);picked=[...anchors,...ghosts]}else{picked=all.filter(e=>e.state!=='ghost').slice(0,distance===1?18:distance===2?28:38);if(picked.filter(e=>e.state==='known').length<3)picked=[...all.slice(0,24)]}const nodes=[{id:'center',name:'YOUR TASTE',type:'center',state:'center',affinity:1,exposure:1,white:0,bridge:1,matched:[]} ,...picked];const links=picked.map(e=>({source:'center',target:e.id,strength:e.affinity}));for(let i=0;i<picked.length;i++)for(let j=i+1;j<picked.length;j++){const shared=picked[i].tags.filter(t=>picked[j].tags.includes(t)).length;if(shared>=2&&links.length<70)links.push({source:picked[i].id,target:picked[j].id,strength:shared/5})}return{nodes,links}}
function renderGraph(){
  const wrap=$('#graph');wrap.innerHTML='';
  const {nodes,links}=graphData();
  $('#mapTitle').textContent=mode==='world'?'My World':'My Whitespace';
  $('#graphStatus').textContent=`${Math.max(0,nodes.length-1)} nodes · ${links.length} connections`;
  if(nodes.length<=1){wrap.innerHTML='<div style="padding:50px;font:500 12px DM Mono;color:#777">Add signals above to build your graph.</div>';renderWhitespace([]);return}
  const w=wrap.clientWidth||760,h=wrap.clientHeight||655,cx=w/2,cy=h/2;
  const ns='http://www.w3.org/2000/svg';
  const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',mode==='world'?'Your taste graph':'Your taste whitespace graph');wrap.appendChild(svg);
  const root=document.createElementNS(ns,'g');svg.appendChild(root);
  const center=nodes[0],others=nodes.slice(1);
  center.x=cx;center.y=cy;
  const positions={center};
  others.forEach((n,i)=>{
    const ring=i<Math.ceil(others.length*.48)?1:2;
    const ringItems=others.filter((_,j)=>(j<Math.ceil(others.length*.48)?1:2)===ring);
    const ringIndex=ringItems.indexOf(n);
    const radius=ring===1?Math.min(w,h)*.23:Math.min(w,h)*.39;
    const angle=(Math.PI*2*ringIndex/Math.max(1,ringItems.length))+(ring===2?.19:0);
    n.x=cx+Math.cos(angle)*radius;n.y=cy+Math.sin(angle)*radius;
    positions[n.id]=n;
  });
  links.forEach(l=>{const a=positions[typeof l.source==='object'?l.source.id:l.source],b=positions[typeof l.target==='object'?l.target.id:l.target];if(!a||!b)return;const line=document.createElementNS(ns,'line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('stroke','#aaa49a');line.setAttribute('stroke-opacity',String(.12+Math.min(.24,(l.strength||0)*.25)));line.setAttribute('stroke-width','1');root.appendChild(line)});
  nodes.forEach(n=>{
    const group=document.createElementNS(ns,'g');group.setAttribute('transform',`translate(${n.x},${n.y})`);group.style.cursor=n.id==='center'?'default':'pointer';
    const circle=document.createElementNS(ns,'circle');const r=n.id==='center'?42:Math.max(11,13+n.affinity*14);circle.setAttribute('r',r);
    circle.setAttribute('fill',n.id==='center'?'#171713':n.state==='known'?(CATEGORIES[n.type]?.[1]||'#333'):'#f3efe8');circle.setAttribute('stroke',n.id==='center'?'#171713':CATEGORIES[n.type]?.[1]||'#777');circle.setAttribute('stroke-width',n.state==='adjacent'?'2':n.state==='ghost'?'1.4':'1');if(n.state==='ghost')circle.setAttribute('stroke-dasharray','4 4');circle.setAttribute('opacity',n.state==='ghost'?'.48':'1');group.appendChild(circle);
    const text=document.createElementNS(ns,'text');text.textContent=n.name;text.setAttribute('x',n.id==='center'?'0':String(r+6));text.setAttribute('y','4');text.setAttribute('text-anchor',n.id==='center'?'middle':'start');text.setAttribute('font-size',n.id==='center'?'10':'9');text.setAttribute('font-weight',n.id==='center'?'700':'500');text.setAttribute('fill',n.id==='center'?'white':n.state==='ghost'?'#777':'#24231f');group.appendChild(text);
    if(n.id!=='center')group.addEventListener('click',()=>{selected=n;renderInspector(n)});root.appendChild(group)
  });
  let scale=1,panX=0,panY=0,dragging=false,lastX=0,lastY=0;const apply=()=>root.setAttribute('transform',`translate(${panX} ${panY}) scale(${scale})`);
  svg.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.65,Math.min(2.2,scale+(e.deltaY<0?.1:-.1)));apply()},{passive:false});
  svg.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;svg.setPointerCapture?.(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!dragging)return;panX+=e.clientX-lastX;panY+=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;apply()});svg.addEventListener('pointerup',()=>dragging=false);svg.addEventListener('pointercancel',()=>dragging=false);
  renderWhitespace(classified().filter(e=>e.state==='ghost').slice(0,8));
}
function renderInspector(e){const kind=e.state==='ghost'?'WHITESPACE':e.state==='known'?'KNOWN':'ADJACENT';$('#inspectorType').textContent=`${kind} / ${CATEGORIES[e.type]?.[0]||e.type}`;$('#inspectorTitle').textContent=e.name;$('#inspectorDescription').textContent=e.description;$('#fitScore').textContent=Math.round(e.affinity*100);$('#exposureScore').textContent=Math.round(e.exposure*100);$('#whiteScore').textContent=Math.round(e.white*100);const matched=e.matched.length?e.matched.join(', '):'your broader active clusters';$('#whyText').textContent=e.state==='ghost'?`Strong fit around ${matched}, but little direct evidence that you already know this. It bridges ${Math.max(1,Math.round(e.bridge*4))} parts of your taste.`:`Connected through ${matched}. ${e.state==='known'?'We found direct evidence of exposure.':'It sits close to your current model, with some room to explore.'}`;renderEntryRamp(e)}
function renderEntryRamp(e){const q=encodeURIComponent(e.name);const maps=(e.type==='place'||e.type==='restaurant')?`<a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${q}">GO · Maps ↗</a>`:'';$('#entryRamp').innerHTML=`<span>ENTER THIS WORLD</span><div class="entry-links"><a target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${q}">WATCH · YouTube ↗</a><a target="_blank" rel="noopener" href="https://www.google.com/search?q=${q}">READ · Search ↗</a><a target="_blank" rel="noopener" href="https://www.google.com/search?q=${encodeURIComponent(e.name+' instagram creators')}">FOLLOW · creators ↗</a>${maps}</div>`}
function renderWhitespace(items){const grid=$('#whitespaceGrid');if(!items.length){grid.innerHTML='<div class="white-card"><span class="ghost-mark">◌</span><h3>No whitespace yet</h3><p>Add and review more signals so the model can identify high-fit areas with low prior exposure.</p></div>';return}grid.innerHTML=items.map(e=>`<article class="white-card" data-id="${e.id}"><span class="ghost-mark">◌</span><h3>${esc(e.name)}</h3><p>${esc(e.description)}</p><div class="white-stats"><span><b>${Math.round(e.affinity*100)}</b>FIT</span><span><b>${Math.round(e.exposure*100)}</b>EXPOSURE</span><span><b>${Math.round(e.white*100)}</b>WHITE</span></div></article>`).join('');grid.querySelectorAll('.white-card[data-id]').forEach(c=>c.onclick=()=>{mode='whitespace';syncMode();const e=classified().find(x=>String(x.id)===c.dataset.id);if(e){selected=e;renderInspector(e);renderGraph();$('#map').scrollIntoView({behavior:'smooth'})}})}
function renderAll(){renderInbox();renderSummary();renderFilters();renderGraph();const sources=[...new Set(signals.flatMap(s=>s.sources))];$('#connectionStatus').textContent=sources.length?`Active evidence: ${sources.join(' · ')} · ${signals.length} detected signals`:'No behavioral sources imported yet.'}
function syncMode(){$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));renderGraph()}
function title(s){return s.replace(/\b\w/g,m=>m.toUpperCase())}function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}

$$('[data-import-source]').forEach(b=>b.onclick=()=>{pendingSource=b.dataset.importSource;$('#signalFileInput').click()});
$('#signalFileInput').onchange=e=>{if(e.target.files.length)importFiles([...e.target.files],pendingSource);e.target.value=''};
$('#manualForm').onsubmit=e=>{e.preventDefault();const v=$('#manualInput').value;v.split(/[,;\n]+/).map(norm).filter(Boolean).forEach(x=>addSignal(x,6,'manual','current'));$('#manualInput').value='';renderAll();toast('Added to Signal Inbox')};
$('#demoButton').onclick=()=>{signals=JSON.parse(JSON.stringify(DEMO));knownEntities=['Film photography','Mexico City'];save();renderAll();toast('Demo profile loaded')};
$('#clearButton').onclick=()=>{signals=[];knownEntities=[];save();selected=null;renderAll();toast('Local taste profile cleared')};
$('#buildGraphButton').onclick=()=>{$('#map').scrollIntoView({behavior:'smooth'});renderGraph()};
$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;syncMode()});
$('#distanceRange').oninput=e=>{distance=Number(e.target.value);renderGraph()};
$('#nodeActions').onclick=e=>{const a=e.target.closest('[data-node-action]');if(!a||!selected)return;if(a.dataset.nodeAction==='known'){if(!knownEntities.includes(selected.name))knownEntities.push(selected.name);toast('Marked as already known')}if(a.dataset.nodeAction==='more'){addSignal(selected.name,8,'feedback','core');selected.tags.slice(0,2).forEach(t=>addSignal(t,6,'feedback','core'));toast('Boosted this part of your taste')}if(a.dataset.nodeAction==='less'){selected.tags.forEach(t=>{const s=signals.find(x=>x.label===norm(t));if(s)s.weight=Math.max(1,s.weight-2)});toast('Reduced this direction')}save();renderAll()};
renderAll();
