const CATEGORIES={brand:['Brands','#bd6a87'],place:['Places','#687f6c'],creator:['Creators','#7c68a2'],media:['Media','#5c70bf'],product:['Products','#a47c35'],aesthetic:['Aesthetics','#53878a'],restaurant:['Restaurants','#a95649']};
const SOURCE_WEIGHT={manual:6,google:8,youtube:7,social:6,places:9,browser:3};
const ENTITIES=[
['Kissaten','restaurant',['tokyo','coffee','jazz','analog','design','ritual'],'Old-school Japanese listening cafés built around coffee, records and intentional atmosphere.'],
['Listening bars','aesthetic',['jazz','music','analog','nightlife','design','tokyo'],'High-intent social spaces where sound systems and listening rituals are the point.'],
['Apartamento','media',['design','magazine','interiors','editorial','photography','global'],'A design magazine built around lived-in interiors, creative people and intimate photography.'],
['MUBI','media',['film','cinema','editorial','art','global','design'],'Film curation as identity: cinema, criticism and a very designed editorial world.'],
['Casa Barragán','place',['mexico city','architecture','color','modernism','design','travel'],'Luis Barragán’s house: saturated color, shadow and emotional modernism.'],
['Contramar','restaurant',['mexico city','food','seafood','design','fashion','travel'],'A Mexico City institution where food, sunlight and a cultural crowd create durable social signal.'],
['Laila Gohar','creator',['food','design','fashion','new york','art','surreal'],'Turns food and tables into playful editorial objects and social sculpture.'],
['Gohar World','brand',['food','fashion','objects','design','new york','surreal'],'Table objects and rituals treated with the energy of a fashion collection.'],
['Paloma Wool','brand',['barcelona','fashion','editorial','mediterranean','art','color'],'Barcelona fashion label operating like an art project and image world.'],
['Gimaguas','brand',['barcelona','fashion','mediterranean','travel','youth','color'],'Mediterranean fashion with beach-city energy and internet-native styling.'],
['Lemaire','brand',['paris','minimal','fashion','design','quiet luxury'],'Soft utility, thoughtful proportions and cultured Paris restraint.'],
['Auralee','brand',['tokyo','minimal','fashion','textile','quiet luxury'],'Japanese material obsession with understated silhouette and color.'],
['Bode','brand',['new york','craft','heritage','textile','editorial','nostalgia'],'Quilted storytelling, antique textiles and downtown New York craft culture.'],
['The Row','brand',['new york','quiet luxury','minimal','fashion','design','editorial'],'Extreme restraint, material quality and status without logos.'],
['Dimes','restaurant',['new york','downtown','wellness','design','fashion','internet'],'Downtown Manhattan restaurant shorthand for an entire creative micro-scene.'],
['Via Carota','restaurant',['new york','west village','italian','food','heritage','design'],'West Village Italian warmth where simplicity carries social signal.'],
['Cafe Cecilia','restaurant',['london','food','fashion','editorial','design'],'East London cooking with a fashion-editorial crowd and stripped-back visual language.'],
['La Buvette','restaurant',['paris','natural wine','wine','food','design','casual'],'Tiny Paris wine-bar energy: informal, high taste, almost anti-luxury.'],
['Tokyo','place',['japan','design','fashion','food','analog','retail','travel'],'A city of extreme specificity: retail ritual, subculture, design and obsessive craft.'],
['Mexico City','place',['mexico','architecture','design','food','art','color','travel'],'A dense collision of modernism, food, craft and contemporary creative culture.'],
['Barcelona','place',['spain','mediterranean','design','fashion','architecture','travel'],'Mediterranean creative city where art, fashion and everyday life blur together.'],
['Copenhagen','place',['denmark','design','food','fashion','minimal','cycling'],'Everyday utility and high taste unusually close together.'],
['Mallorca','place',['spain','mediterranean','travel','design','slow','sun'],'Island design culture mixing rustic materiality with new creative hospitality.'],
['Dover Street Market','place',['retail','fashion','london','tokyo','art','design'],'Retail as cultural curation rather than inventory.'],
['Film photography','aesthetic',['analog','photography','nostalgia','imperfection','travel','editorial'],'A slower image language where grain and limitation make pictures feel intentional.'],
['Natural wine','aesthetic',['wine','food','design','casual','creative','anti-luxury'],'A taste ecosystem connecting restaurants, labels, ceramics, farming and creative scenes.'],
['Analog internet','aesthetic',['analog','internet','nostalgia','editorial','objects','media'],'Digital culture fetishizing physical media, tactility and slowness.'],
['Quiet luxury','aesthetic',['minimal','luxury','materials','fashion','design','status'],'Status through material, cut and insider recognition rather than logos.'],
['Mediterranean modernism','aesthetic',['mediterranean','architecture','sun','design','travel','minimal'],'Warm modernism built from stone, color, shade and relaxed geometry.'],
['Modernist ceramics','product',['ceramics','design','home','craft','food','art','objects'],'Useful objects that signal material sensitivity without looking decorative for decoration’s sake.'],
['Hotel stationery','product',['travel','design','paper','nostalgia','hotel','objects'],'Ephemeral branded objects that turn a trip into a physical archive.'],
['Point-and-shoot cameras','product',['photography','analog','nostalgia','compact','travel','internet'],'Small cameras prized for immediacy, imperfect flash and low-friction memory making.'],
['Contax T2','product',['photography','analog','fashion','luxury','compact','editorial'],'A compact film camera that became an object of fashion-world taste.'],
['Olive oil culture','product',['food','mediterranean','design','packaging','wellness','status'],'A pantry staple becoming an aesthetic product through origin, ritual and packaging.'],
['Portuguese tinned fish','product',['food','design','packaging','heritage','travel','objects'],'Everyday pantry product elevated by graphic design, ritual and travel nostalgia.'],
['Sofia Coppola','creator',['film','fashion','women','nostalgia','quiet','editorial'],'Soft-focus worlds of girlhood, privilege, melancholy and immaculate objects.'],
['Juergen Teller','creator',['photography','fashion','editorial','raw','analog','art'],'Anti-glamour fashion photography whose imperfection became its own status code.'],
['The Gentlewoman','media',['magazine','women','fashion','editorial','design','london'],'Long-form portraits with disciplined typography and understated fashion intelligence.'],
['PIN–UP','media',['architecture','magazine','design','fashion','editorial','new york'],'Architecture publishing with fashion-world wit and visual experimentation.'],
['Noma Projects','brand',['copenhagen','food','design','fermentation','product','editorial'],'Restaurant R&D translated into packaged products with cultural credibility.'],
['Aesop','brand',['beauty','design','retail','architecture','minimal','global'],'A retail system where store architecture and language became as important as the product.'],
['Byredo','brand',['beauty','fashion','design','minimal','editorial','luxury'],'Fragrance built through art direction, culture and visual minimalism.'],
['Mahjong revival','aesthetic',['game','heritage','community','design','diaspora','social'],'A heritage social ritual being reinterpreted through younger communities, design and identity.'],
['Kinfolk','media',['magazine','minimal','design','lifestyle','photography','copenhagen'],'A highly recognizable slow-living visual language that shaped a decade of internet minimalism.'],
['Erewhon','place',['los angeles','wellness','food','status','internet','consumer'],'A grocery store functioning as a status surface for wellness and consumer culture.'],
['Matcha','product',['japan','wellness','drink','design','ritual','internet'],'A drink whose ritual, color and café design make it unusually legible online.'],
['Vintage Porsche','product',['cars','heritage','design','status','analog','nostalgia'],'Mechanical charm, timeless proportions and enthusiast credibility.']
].map((e,i)=>({id:i,name:e[0],type:e[1],tags:e[2],description:e[3]}));

const DEMO=[
 {label:'film photography',weight:9,sources:['youtube','social'],role:'core'},
 {label:'mexico city',weight:8,sources:['places','google'],role:'core'},
 {label:'design',weight:9,sources:['browser','social'],role:'core'},
 {label:'fashion',weight:8,sources:['social'],role:'core'},
 {label:'natural wine',weight:7,sources:['places','social'],role:'core'},
 {label:'jazz',weight:5,sources:['youtube'],role:'current'},
 {label:'ceramics',weight:5,sources:['google','browser'],role:'current'},
 {label:'tokyo',weight:4,sources:['youtube','google'],role:'current'}
];
