let signals=load('itg-signals',[]);let knownEntities=load('itg-known',[]);let mode='world';let activeTypes=new Set(Object.keys(CATEGORIES));let selected=null;let pendingSource='browser';let distance=2;

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(){localStorage.setItem('itg-signals',JSON.stringify(signals));localStorage.setItem('itg-known',JSON.stringify(knownEntities))}
function norm(s){return String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)}
function addSignal(label,weight=6,source='manual',role='current'){label=norm(label);if(!label||label.length<2)return;const hit=signals.find(s=>s.label===label);if(hit){hit.weight=Math.min(10,hit.weight+Math.max(1,Math.round(weight/3)));if(!hit.sources.includes(source))hit.sources.push(source)}else signals.push({label,weight:Math.max(1,Math.min(10,Math.round(weight))),sources:[source],role});save()}
function tokenize(text){const clean=norm(text);const found=[];const phrases=new Set(ENTITIES.flatMap(e=>[e.name,...e.tags]).map(norm));phrases.forEach(p=>{if(p.length>3&&clean.includes(p))found.push(p)});const words=clean.split(' ').filter(w=>w.length>4&&!['https','google','youtube','instagram','tiktok','search','watch','history','www'].includes(w));const counts={};words.forEach(w=>counts[w]=(counts[w]||0)+1);Object.entries(counts).filter(([,c])=>c>2).sort((a,b)=>b[1]-a[1]).slice(0,12).forEach(([w])=>found.push(w));return [...new Set(found)].slice(0,28)}
async function ensureZip(){if(window.JSZip)return true;return await new Promise(resolve=>{const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';sc.onload=()=>resolve(true);sc.onerror=()=>resolve(false);document.head.appendChild(sc)})}
async function importFiles(files,source){let total=0;for(const file of files){let chunks=[];if(file.name.toLowerCase().endsWith('.zip')){const ok=await ensureZip();if(!ok){toast('ZIP helper could not load — try JSON, CSV, HTML or TXT');continue}const zip=await JSZip.loadAsync(file);for(const name of Object.keys(zip.files)){const z=zip.files[name];if(!z.dir&&/\.(json|csv|txt|html|htm)$/i.test(name)){try{chunks.push(await z.async('text'))}catch{}}}}else{try{chunks.push(await file.text())}catch{}}for(const chunk of chunks){tokenize(chunk).forEach(k=>{addSignal(k,SOURCE_WEIGHT[source]||4,source,'core');total++})}}renderAll();toast(total?`Added ${total} signal matches from ${source}`:'No recognizable taste signals found in that export')}
function signalAffinity(entity){let total=0,max=0,matched=[];for(const s of signals){if(s.role==='muted')continue;const mult=s.role==='core'?1:s.role==='current'?.78:.55;const sl=norm(s.label);const sTokens=sl.split(' ');const hay=[norm(entity.name),...entity.tags.map(norm)];let hit=hay.some(h=>h===sl||h.includes(sl)||sl.includes(h));if(!hit)hit=hay.some(h=>sTokens.some(t=>t.length>3&&h.includes(t)));if(hit){const v=s.weight*mult;total+=v;max+=10;matched.push(s.label)}}const score=max?Math.min(1,total/Math.max(16,max*.65)):0;return{score,matched:[...new Set(matched)].slice(0,4)}}
function exposure(entity){if(knownEntities.includes(entity.name))return 1;const name=norm(entity.name);let x=0;for(const s of signals){if(s.role==='muted')continue;const sl=norm(s.label);if(sl===name)x=Math.max(x,s.role==='core'?.9:.65);else if(entity.tags.some(t=>norm(t)===sl))x=Math.max(x,s.role==='core'?.34:.18)}return x}
function bridge(entity){const groups={};for(const s of signals){if(s.role==='muted'||s.weight<5)continue;for(const tag of entity.tags){const t=norm(tag),sl=norm(s.label);if(t.includes(sl)||sl.includes(t)){const g=tag.split(' ')[0];groups[g]=1}}}const n=Object.keys(groups).length;return Math.min(1,.28+n*.22)}
function metrics(entity){const a=signalAffinity(entity),ex=exposure(entity),br=bridge(entity);const white=Math.max(0,a.score*br*(1-ex));return{affinity:a.score,matched:a.matched,exposure:ex,bridge:br,white}}
function classified(){return ENTITIES.map(e=>({...e,...metrics(e)})).map(e=>({...e,state:e.exposure>.55?'known':e.white>.16&&e.exposure<.36?'ghost':'adjacent'})).sort((a,b)=>mode==='whitespace'?b.white-a.white:b.affinity-a.affinity)}
function topClusters(){const map={};for(const s of signals){if(s.role==='muted')continue;map[s.label]=(map[s.label]||0)+s.weight*(s.role==='core'?1:.75)}return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,6)}
